export const SET_LOGIN_VALUE = 'SET_LOGIN_VALUE';
export const SET_PASSWORD_VALUE = 'SET_PASSWORD_VALUE';
export const SET_LOGIN_INVALID = 'SET_LOGIN_INVALID';
export const SET_PASSWORD_INVALID = 'SET_PASSWORD_INVALID';
export const CLEAR_FORM = 'CLEAR_FORM';
